### ISSUE TITLE
Combo boxes not working properly on dark theme

### ISSUE THREAD

**Issue by eliandoran** [eliandoran/breeze-trilium#4]
![image](https://github.com/eliandoran/breeze-trilium/assets/21236836/2108e2e3-8aac-4402-988e-3cb2dcad8b7d)

**Comment by zerebos** [comment]
I'm currently just doing this locally to match the theme
```css
select.form-control option {
    background: var(--breeze-button-background-end);
}
```
![image](https://github.com/eliandoran/breeze-trilium/assets/6865942/7d994c2a-68c8-46e2-9f6f-b4ce0348d7b5)
