### ISSUE TITLE
No tooltips for launcher entries (fix included)

### ISSUE THREAD

**Issue by FliegendeWurst** [eliandoran/breeze-trilium#6]
First of all, I have to say that this theme is simply amazing! It must have been a lot of work to mirror the Breeze style using only CSS / Less, all whilst working around the document structure provided by Trilium.

I only noticed one minor issue:

![image](https://github.com/eliandoran/breeze-trilium/assets/12560461/a11234cf-8890-4899-8764-3426871ddc67)

As you can see there is no tooltip to remind me of the launcher's function. It's not that important (I know all my launchers), but I have some with identical icons.

It is fixable with this bit of CSS, which will put the tooltip below the button (annoying side effect: even the buttons with labels get tooltips).
```css
.tooltip.bs-tooltip-right {
  position: absolute;
  left: calc(-4px + calc(-1 * var(--breeze-iconbutton-width))) !important;
  top: var(--breeze-iconbutton-width) !important;
}
```
Whilst removing this bit
https://github.com/eliandoran/breeze-trilium/blob/c426543d8ba63dfa40a961c31ee9fb5678d48834/src/toolbar.less#L180-L185
