### ISSUE TITLE
"Advanced" dropdown menu off the screen (fix included)

### ISSUE THREAD

**Issue by FliegendeWurst** [eliandoran/breeze-trilium#7]
The "Advanced" submenu in the global hamburger menu extends off the screen.

This CSS fixes it:
```css
.dropdown-menu:has(.open-dev-tools-button) {
    transform: translate(-100%, 0);
}
```
Which will move the dropdown submenu onto the main dropdown menu. (Still not perfect UX-wise, but better than before)

By the way, the theme also runs well without the native title bar. At least on my setup, the most essential controls are present as floating buttons:
![image](https://github.com/eliandoran/breeze-trilium/assets/12560461/41f79803-1117-42de-85a7-a5242ac0da91)
To move the window around it is possible to hold `Alt` and drag the window.
